### ISSUE TITLE
Assignments crashing when used as "separate"

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/com.ninetwozero.bf4intel#16]
```
Process: com.ninetwozero.bf4intel, PID: 17464
java.lang.NoClassDefFoundError: com/ninetwozero/bf4intel/assignments/Assignments
    at java.lang.Class.getDeclaredMethods(Native Method)
    at java.lang.Class.getDeclaredMethods(Class.java:656)
    at com.squareup.otto.AnnotatedHandlerFinder.loadAnnotatedMethods(AnnotatedHandlerFinder.java:52)
    at com.squareup.otto.AnnotatedHandlerFinder.findAllProducers(AnnotatedHandlerFinder.java:119)
    at com.squareup.otto.HandlerFinder$1.findAllProducers(HandlerFinder.java:33)
    at com.squareup.otto.Bus.register(Bus.java:191)
    at com.ninetwozero.bf4intel.assignments.AssignmentsFragment.onResume(AssignmentsFragment.java:33)
    at android.support.v4.app.Fragment.performResume(Fragment.java:1503)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1070)
    at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1871)
    at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:455)
    at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:444)
    at android.app.Activity.performResume(Activity.java:5335)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2759)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2798)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2231)
    at android.app.ActivityThread.access$700(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4998)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ninetwozero.bf4intel.assignments.Assignments" on path: DexPathList[[zip file "/data/app/com.ninetwozero.bf4intel-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.ninetwozero.bf4intel-1, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    at java.lang.Class.getDeclaredMethods(Native Method)
    at java.lang.Class.getDeclaredMethods(Class.java:656)
    at com.squareup.otto.AnnotatedHandlerFinder.loadAnnotatedMethods(AnnotatedHandlerFinder.java:52)
    at com.squareup.otto.AnnotatedHandlerFinder.findAllProducers(AnnotatedHandlerFinder.java:119)
    at com.squareup.otto.HandlerFinder$1.findAllProducers(HandlerFinder.java:33)
    at com.squareup.otto.Bus.register(Bus.java:191)
    at com.ninetwozero.bf4intel.assignments.AssignmentsFragment.onResume(AssignmentsFragment.java:33)
    at android.support.v4.app.Fragment.performResume(Fragment.java:1503)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1070)
    at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1871)
    at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:455)
    at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:444)
    at android.app.Activity.performResume(Activity.java:5335)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2759)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2798)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2231)
    at android.app.ActivityThread.access$700(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4998)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
    at dalvik.system.NativeStart.main(Native Method)
```

Any thoughts @peter-budo? It's crashing when it's trying to register for the bus.

**Comment by peter-budo** [comment]
What are you doing there?

**Comment by peter-budo** [comment]
Try APK from build server (http://ci.peterscorner.co.uk/job/BF4%20Intel/ws/BF4Intel/build/apk/) and let me know how it goes

**Comment by karllindmark** [comment]
@peter-budo: Build Server APK works OK. However, it doesn't anymore when all fragments & co are support.v4. HMmmm.

**Comment by karllindmark** [comment]
@peter-budo: #17 contains the code being used

**Comment by karllindmark** [comment]
Related to JDK7. Using JDK6 solves this issue.

**Comment by peter-budo** [comment]
The puzzles clicks together. When I transferred Bf3-Droid to Gradle I was fresh after Gradle training and running JDK 7. I had issues with core module classes if you recall, but I couldn't understand why. Now we know :wink:

**Comment by karllindmark** [comment]
:+1:
