### ISSUE TITLE
Assignment detail crash

### ISSUE THREAD

**Issue by peter-budo** [ninetwozero/com.ninetwozero.bf4intel#189]
Steps to reproduce

1. Open app
2. Make sure you have soldier
3. Open assignments
4. Scroll down to single mission assignments that are at the end
5. Tap to open single mission assignment to see details
6. App crashes

````
Process:com.ninetwozero.bf4intel,PID:28951
        java.lang.RuntimeException:Unable to start activity ComponentInfo{com.ninetwozero.bf4intel/com.ninetwozero.bf4intel.ui.activities.SingleFragmentActivity}:java.lang.IndexOutOfBoundsException:Invalid index 0,size is 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        Caused by:java.lang.IndexOutOfBoundsException:Invalid index 0,size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.ninetwozero.bf4intel.ui.assignments.AssignmentDetailFragment.populateAwardRequirements(AssignmentDetailFragment.java:185)
        at com.ninetwozero.bf4intel.ui.assignments.AssignmentDetailFragment.populateViews(AssignmentDetailFragment.java:90)
        at com.ninetwozero.bf4intel.ui.assignments.AssignmentDetailFragment.initialize(AssignmentDetailFragment.java:70)
        at com.ninetwozero.bf4intel.ui.assignments.AssignmentDetailFragment.onCreateView(AssignmentDetailFragment.java:64)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
        at android.app.Activity.performStart(Activity.java:6268)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
````

**Comment by karllindmark** [comment]
Thought based on stacktrace - the assignment doesn't have any
prerequisites? 🤔

**Comment by peter-budo** [comment]
Yeah, there been something in the past I was fixing already and I guess I forgot about it when I did change with expansion icons fix
