### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/com.ninetwozero.bf4intel#53]
``` bash
java.lang.NullPointerException
at java.util.Collections.sort(Collections.java:1866)
at com.ninetwozero.bf4intel.ui.awards.AwardGridFragment.fetchSortedAwards(AwardGridFragment.java:98)
at com.ninetwozero.bf4intel.ui.awards.AwardGridFragment.processAwards(AwardGridFragment.java:90)
at com.ninetwozero.bf4intel.ui.awards.AwardGridFragment.setupGrid(AwardGridFragment.java:86)
at com.ninetwozero.bf4intel.ui.awards.AwardGridFragment.processResult(AwardGridFragment.java:75)
at com.ninetwozero.bf4intel.ui.awards.AwardGridFragment.onLoadSuccess(AwardGridFragment.java:69)
at com.ninetwozero.bf4intel.base.ui.BaseLoadingFragment.onLoadFinished(BaseLoadingFragment.java:32)
at com.ninetwozero.bf4intel.base.ui.BaseLoadingFragment.onLoadFinished(BaseLoadingFragment.java:19)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
at android.support.v4.content.Loader.deliverResult(Loader.java:104)
at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:5751)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by peter-budo** [comment]
Already on [PivotalTracker](https://www.pivotaltracker.com/story/show/66569402) , no point to push it on github
